# Generated by Django 5.2.8 on 2025-12-07 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_supplier'),
        ('suppliers', '0002_alter_supplier_options_alter_supplier_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.variant'),
        ),
    ]
