# Generated by Django 5.2.8 on 2025-12-02 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_date', models.DateField(unique=True)),
                ('day_of_week', models.CharField(max_length=10, null=True)),
                ('month_name', models.CharField(max_length=20, null=True)),
                ('quarter', models.PositiveSmallIntegerField(null=True)),
                ('is_holiday', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DimProductBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('rating', models.PositiveSmallIntegerField(default=1)),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_exciting', models.BooleanField(default=False)),
                ('free_shipping', models.BooleanField(default=False)),
                ('has_gift', models.BooleanField(default=False)),
                ('is_budget_friendly', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('category_level_1', models.CharField(blank=True, max_length=255, null=True)),
                ('category_level_2', models.CharField(blank=True, max_length=255, null=True)),
                ('category_level_3', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DimUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=150)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_date', models.DateField()),
                ('age_range', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimVariantOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.IntegerField()),
                ('variant_sku', models.CharField(max_length=100, unique=True)),
                ('product_id', models.IntegerField()),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.PositiveIntegerField(help_text='Price of one unit')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, help_text='0-100%')),
                ('total_price', models.PositiveIntegerField(editable=False, null=True)),
                ('total_after_discount', models.PositiveIntegerField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FactSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.PositiveIntegerField(null=True)),
                ('total_price_after_discount', models.PositiveIntegerField(null=True)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.dimdate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.dimuser')),
                ('variants', models.ManyToManyField(to='analytics.dimvariantorder')),
            ],
        ),
    ]
