# Generated by Django 5.2.8 on 2025-12-03 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimdate',
            name='jalali_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
