# Generated by Django 5.2.8 on 2025-12-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_dimdate_jalali_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimdate',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dimdate',
            name='is_holiday',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='dimdate',
            name='month_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dimdate',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
