# Generated by Django 5.2.8 on 2025-12-03 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_dimdate_day_of_week_alter_dimdate_is_holiday_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dimdate',
            table='DimDate',
        ),
        migrations.AlterModelTable(
            name='dimproductbase',
            table='DimProductBase',
        ),
        migrations.AlterModelTable(
            name='dimuser',
            table='DimUser',
        ),
        migrations.AlterModelTable(
            name='dimvariantorder',
            table='DimVariantOrder',
        ),
        migrations.AlterModelTable(
            name='factsales',
            table='FactSales',
        ),
    ]
