# Generated by Django 5.2.8 on 2025-12-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_dimdate_table_alter_dimproductbase_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsales',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
