# Generated by Django 5.2.8 on 2025-12-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_factsales_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsales',
            name='status',
            field=models.CharField(choices=[('initial', 'ثبت اولیه'), ('process', 'در حال پردازش'), ('sent', 'ارسال شده'), ('done', 'تکمیل شده'), ('cancel', 'لغو شده'), ('rejected', 'مرجوع شده')], max_length=20, null=True),
        ),
    ]
