# Generated by Django 5.2.8 on 2025-12-03 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_factsales_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_order_quantity', models.IntegerField(default=0)),
                ('process_order_quantity', models.IntegerField(default=0)),
                ('sent_order_quantity', models.IntegerField(default=0)),
                ('done_order_quantity', models.IntegerField(default=0)),
                ('cancel_order_quantity', models.IntegerField(default=0)),
                ('rejected_order_quantity', models.IntegerField(default=0)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='analytics.dimdate')),
            ],
            options={
                'db_table': 'FactAnalytics',
            },
        ),
    ]
