# Generated by Django 5.2.8 on 2025-12-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_factanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='factsales',
            name='exclude_from_analytics',
            field=models.BooleanField(default=False),
        ),
    ]
