# Generated by Django 5.2.8 on 2025-12-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_factsales_exclude_from_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='factanalytics',
            name='initial_order_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
