# Generated by Django 5.2.8 on 2025-12-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_factanalytics_initial_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimproductbase',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
