# Generated by Django 5.2.8 on 2025-12-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agerange',
            table='AgeRange',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
