# Generated by Django 5.2.8 on 2025-12-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_synced_analytics',
            field=models.BooleanField(default=False),
        ),
    ]
