# Generated by Django 5.2.8 on 2025-12-02 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_is_synced_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-100%', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
