# Generated by Django 5.2.8 on 2025-12-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_discount_percent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderitem',
            table='OrderItem',
        ),
    ]
