# Generated by Django 5.2.8 on 2025-12-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_created_at_alter_order_updated_at_and_more'),
        ('products', '0004_variantinvoicequantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemVariantInvoiceQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deducted_quantity', models.PositiveIntegerField(default=0)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_invoice_quantities', to='orders.orderitem')),
                ('variant_invoice_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='products.variantinvoicequantity')),
            ],
            options={
                'verbose_name': 'Order Item Variant Invoice Quantity',
                'verbose_name_plural': 'Order Item Variant Invoice Quantities',
                'db_table': 'OrderItemVariantInvoiceQuantity',
            },
        ),
    ]
