# Generated by Django 5.2.8 on 2025-12-07 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_brand_supplier'),
        ('suppliers', '0003_remove_purchaseitem_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantInvoiceQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_quantities', to='suppliers.purchaseinvoice')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_invoice_quantities', to='products.variant')),
            ],
            options={
                'verbose_name': 'Variant Invoice Quantity',
                'verbose_name_plural': 'Variant Invoice Quantities',
                'db_table': 'VariantInvoiceQuantity',
                'unique_together': {('variant', 'invoice')},
            },
        ),
    ]
